version: '3.5'

services:

  frontend:
    container_name: frontend
    image: pedrofff/angular
    volumes:
      - angular:/app
    ports:
      - "80:80"

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - --interval 30

volumes:
  angular:
    external: true
